site_name: Bolt Runtime Engine Documentation
site_description: Official documentation for the Bolt programming language
site_author: Swifteex Studio

site_url: https://SwifteexStudio.github.io/bolt-docs/

docs_dir: main
site_dir: site

use_directory_urls: true

nav:
  - Home: index.md
  - Native Syntax: syntax.md
  - Modules: modules.md
  - Bfile: bfiledocs.md

theme:
  name: material

  palette:
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Switch to dark mode

    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode

  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.top
    - search.highlight
    - search.share
    - content.code.copy

markdown_extensions:
  - toc:
      permalink: true
  - tables
  - fenced_code
  - codehilite
  - admonition
  - attr_list
  - md_in_html
  - pymdownx.superfences
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.tabbed
  - pymdownx.details
